# Generated by Django 5.1.4 on 2025-09-30 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='tbl_categories',
        ),
        migrations.AlterModelTable(
            name='product',
            table='tbl_products',
        ),
    ]
